apiVersion: v1
kind: Service
metadata:
  name: vite-demo
  labels:
    app.kubernetes.io/name: vite-demo
spec:
  selector:
    app.kubernetes.io/name: vite-demo
  ports:
    - name: http
      port: 80
      targetPort: http
