apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# This label makes the environment visible in kubectl and Argo CD.
labels:
- pairs:
    app.kubernetes.io/environment: dev

  # Jenkins changes only newTag after each direct branch push.
images:
- name: ghcr.io/pils10/vite-demo
  newName: ghcr.io/pils10/vite-demo
  newTag: dev-main-a9d5e3428fa1

replicas:
- count: 1
  name: vite-demo
